package GUI;

/**
 *
 * @author QUANG DIEN
 */
import MyDesign.Model_Menu;
import MyDesign.EventMenuSelected;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import javax.swing.JFrame;

public class Menu extends javax.swing.JPanel {
    
    private EventMenuSelected event;

    public void addEventMenuSelected(EventMenuSelected event){
        this.event = event;
        list_Menu1.addEventMenuSelected(event); 
    }
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setOpaque(false);
        list_Menu1.setOpaque(false);
        init();
    }

    private void init() {
        list_Menu1.addItem(new Model_Menu("1", "Thống kê ", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("2", "Cho mượn", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("3", "Nhận lại sách", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("4", "Kho", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("5", "Phiếu mượn", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("6", "Độc giả", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("7", "Nhân viên", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("8", "Khác", Model_Menu.MenuType.MENU));
        list_Menu1.addItem(new Model_Menu("9", "Phân quyền", Model_Menu.MenuType.MENU));
        
        list_Menu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
        list_Menu1.addItem(new Model_Menu("", " ", Model_Menu.MenuType.EMPTY));
        list_Menu1.addItem(new Model_Menu("10", "Đăng xuất", Model_Menu.MenuType.MENU));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list_Menu1 = new MyDesign.List_Menu<>();

        setBackground(new java.awt.Color(246, 250, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list_Menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list_Menu1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        Color c = new Color(246,250,255);
        g2.setPaint(c);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyDesign.List_Menu<String> list_Menu1;
    // End of variables declaration//GEN-END:variables
}
