/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import BUS.BookBUS;
import BUS.PayBUS;
import DTO.entities.Book1;
import DTO.entities.BorrowCard;
import DTO.entities.DetailBC;

import MyDesign.ScrollBar;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author QUANG DIEN
 */
public class Pay_GUI extends javax.swing.JPanel {
    private PayBUS pbus;
    private BookBUS bookBUS;
    DefaultTableModel tableModel;
    private BorrowCard bc;
    public static Book1 b__static;
    public static BorrowCard bc__static;     
    public static DetailBC dt__static; 

    /**
     * Creates new form Pay_GUI
     */
    public Pay_GUI() {
        initComponents();
        try {
            pbus = new PayBUS();
            showAll();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        spTicketDetail.setVerticalScrollBar(new ScrollBar());
        spTicketDetail.getVerticalScrollBar().setBackground(Color.WHITE);
        spTicketDetail.getViewport().setBackground(Color.WHITE);
        p.setBackground(Color.WHITE);
        spTicketDetail.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    }
    
    private void showAll(){
        tableModel = (DefaultTableModel)tbSachKhaDung.getModel();
        showBC();
        
    }
     
    private void showBC(){
        try {
            Vector<BorrowCard> list_bc = pbus.getAll();
            
            tableModel.setRowCount(0);
            for (BorrowCard bc : list_bc) {
                Object[] row = {bc.getID(), bc.getReadername(), bc.getStartDate(), bc.getExpReDate(), bc.getStaffname()};
                tableModel.addRow(row); 
            }
            
        } catch (Exception e) {
            e.printStackTrace();
    }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel23 = new javax.swing.JLabel();
        panelBorder1 = new MyDesign.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tbSachKhaDung = new MyDesign.MyTable();
        panelBorder_Basic1 = new MyDesign.PanelBorder_Basic();
        jLabel8 = new javax.swing.JLabel();
        txtSearch = new MyDesign.SearchText();
        spTicketDetail = new javax.swing.JScrollPane();
        panelBorder2 = new MyDesign.PanelBorder();
        lbMaPhieuMuon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDocGia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNgayMuon = new javax.swing.JLabel();
        txtThuKho = new javax.swing.JLabel();
        txtTienCoc = new javax.swing.JLabel();
        lbLine = new javax.swing.JLabel();
        lbBaoMat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JLabel();
        txtTacGia = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JLabel();
        dtgNgayNhan = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        cbSach = new javax.swing.JComboBox<>();
        btnChoMuon = new MyDesign.MyButton();

        jLabel23.setText("jLabel23");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(127, 127, 127));
        jLabel5.setText("Phiếu mượn");

        spTable.setBorder(null);

        tbSachKhaDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Độc giả", "Ngày mượn", "Ngày trả", "Thủ thư"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSachKhaDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSachKhaDungMouseClicked(evt);
            }
        });
        spTable.setViewportView(tbSachKhaDung);
        if (tbSachKhaDung.getColumnModel().getColumnCount() > 0) {
            tbSachKhaDung.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelBorder_Basic1Layout = new javax.swing.GroupLayout(panelBorder_Basic1);
        panelBorder_Basic1.setLayout(panelBorder_Basic1Layout);
        panelBorder_Basic1Layout.setHorizontalGroup(
            panelBorder_Basic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder_Basic1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBorder_Basic1Layout.setVerticalGroup(
            panelBorder_Basic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder_Basic1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelBorder_Basic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelBorder_Basic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(panelBorder_Basic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        spTicketDetail.setBackground(new java.awt.Color(246, 250, 255));
        spTicketDetail.setBorder(null);

        panelBorder2.setPreferredSize(new java.awt.Dimension(217, 327));

        lbMaPhieuMuon.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbMaPhieuMuon.setForeground(new java.awt.Color(22, 113, 221));
        lbMaPhieuMuon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaPhieuMuon.setText("#LB01");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel3.setText("Độc giả");

        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("Thông tin cơ bản");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MÃ PHIẾU MƯỢN");

        txtDocGia.setText("");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel4.setText("Ngày mượn");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel6.setText("Thủ Thư");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setText("Tiền cọc");

        txtNgayMuon.setText("");

        txtThuKho.setText("");

        txtTienCoc.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        txtTienCoc.setText("");

        lbLine.setForeground(new java.awt.Color(204, 204, 204));
        lbLine.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(204, 204, 204)));

        lbBaoMat.setForeground(new java.awt.Color(127, 127, 127));
        lbBaoMat.setText("Báo mất");
        lbBaoMat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(127, 127, 127)));
        lbBaoMat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBaoMatMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel9.setText("Tên sách");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel10.setText("Tác giả");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel11.setText("Số lượng");

        dtgNgayNhan.setToolTipText("");
        dtgNgayNhan.setDateFormatString("yyyy-MM-dd");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Ngày Nhận:");

        cbSach.setBackground(new java.awt.Color(246, 250, 255));
        cbSach.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cbSach.setBorder(null);
        cbSach.setOpaque(true);
        cbSach.setPreferredSize(new java.awt.Dimension(77, 28));

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDocGia, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(txtNgayMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbMaPhieuMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(48, 48, 48)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThuKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dtgNgayNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbLine, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelBorder2Layout.createSequentialGroup()
                                    .addComponent(cbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbBaoMat))
                                .addComponent(jLabel2)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(lbMaPhieuMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDocGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayMuon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtThuKho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTienCoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbLine, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBaoMat)
                    .addComponent(cbSach, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTacGia))
                .addGap(11, 11, 11)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtgNgayNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        spTicketDetail.setViewportView(panelBorder2);

        btnChoMuon.setBackground(new java.awt.Color(22, 113, 221));
        btnChoMuon.setForeground(new java.awt.Color(255, 255, 255));
        btnChoMuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse-white.png"))); // NOI18N
        btnChoMuon.setText("Nhận sách");
        btnChoMuon.setBorderColor(new java.awt.Color(22, 113, 221));
        btnChoMuon.setColor(new java.awt.Color(22, 113, 221));
        btnChoMuon.setColorOver(new java.awt.Color(22, 113, 221));
        btnChoMuon.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnChoMuon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChoMuonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnChoMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spTicketDetail))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spTicketDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnChoMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbBaoMatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBaoMatMouseClicked
        // TODO add your handling code here:
        Component source = (Component) evt.getSource();
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(source);
        
        PayReport_Dialog payReportDialog = new PayReport_Dialog(parent, true);
        payReportDialog.setVisible(true);
        
    }//GEN-LAST:event_lbBaoMatMouseClicked

    private void btnChoMuonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChoMuonMouseClicked
        // TODO add your handling code here:
         Vector<BorrowCard> list;
        try {
            list = pbus.getAll();
            int n= tbSachKhaDung.getSelectedRow();
            if(n != -1){
                int selectedId = (int) tbSachKhaDung.getValueAt(n, 0);

                for (BorrowCard card : list) {
                    if (card.getID() == selectedId) {
                        bc = card;
                        break;
                    }
                }
                Date realDate = dtgNgayNhan.getDate();
                long songayMuon = pbus.CacluteDate(bc.getStartDate(), bc.getExpReDate() );
                long ngayTrathucte = pbus.CacluteDate(realDate,bc.getExpReDate());
                System.out.println(songayMuon +" "+ ngayTrathucte);
                if(ngayTrathucte < 0){
                    //System.out.println("Trả trễ. Ban acc");
                    JOptionPane.showMessageDialog(null, "Trả không đúng hạn! Nộp card 20k!");
                    pbus.RecoverBook(bc);
                }
                else if(ngayTrathucte >0 && ngayTrathucte < songayMuon){
                    //System.out.println("Trả đúng hạn ok ní!");
                    JOptionPane.showMessageDialog(null, "Trả đúng hạn!");
                    pbus.RecoverBook(bc);
                }
                else{
                    //System.out.println("Ngày nhập không đúng thực tế ");
                    JOptionPane.showMessageDialog(null, "Ngày nhận sai thực tế!");
                }
                JOptionPane.showMessageDialog(null, "Nhận thành công!");
            }else{
                JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu mượn! ");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnChoMuonMouseClicked

    private void tbSachKhaDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSachKhaDungMouseClicked

        // TODO add your handling code here:
        Vector<BorrowCard> list;
        try {
            list = pbus.getAll();
            int n = tbSachKhaDung.getSelectedRow();
            int selectedId = (int) tbSachKhaDung.getValueAt(n, 0);
            bc = new BorrowCard();
            for (BorrowCard card : list) {
                if (card.getID() == selectedId) {
                    bc = card;
                    break;
                }
            }
            
            bc__static = bc;
            System.out.print(bc);
            lbMaPhieuMuon.setText("#PM"+bc.getID());
            txtDocGia.setText(bc.getReadername());
            txtNgayMuon.setText(String.valueOf(bc.getStartDate()));
            txtThuKho.setText(bc.getStaffname());
            txtTienCoc.setText(String.valueOf(bc.getdeposit())+"đ");
            txtTenSach.setText("");
            txtTacGia.setText("");
            txtSoLuong.setText("");
            cbSach.removeAllItems();

            for (DetailBC bs : bc.getListBook()) {
                cbSach.addItem(bs.getBookname());
            }

            if (!bc.getListBook().isEmpty()) {
                bookBUS = new BookBUS();
                DetailBC fB = bc.getListBook().get(0);
                b__static = bookBUS.getBookByISBN(fB.getISBN());
                txtTenSach.setText(fB.getBookname());
                String author ="";
                for (Iterator<String> it = fB.getAuthorname().iterator(); it.hasNext();) {
                    author = author + it.next();
                }
                txtTacGia.setText(author);
                txtSoLuong.setText(String.valueOf((char) fB.getNum()));
            }

            cbSach.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    String selectedBookName = (String) cbSach.getSelectedItem();
                    DetailBC selectedBook = null;
                    for (DetailBC bs : bc.getListBook()) {
                        if (bs.getBookname().equals(selectedBookName)) {
                            dt__static = bs;
                            selectedBook = bs;
                            txtTenSach.setText(selectedBook.getBookname());
                            String author ="";
                            for (Iterator<String> it = bs.getAuthorname().iterator(); it.hasNext();) {
                                author = author + it.next();
                            }

                            txtTacGia.setText(author);
                            txtSoLuong.setText(String.valueOf(selectedBook.getNum()));
                        }
                    }
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
    }
    }//GEN-LAST:event_tbSachKhaDungMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
            try {
            String keyword = txtSearch.getText().toLowerCase();
            if (!keyword.isEmpty()) {
                Vector<BorrowCard> kq = pbus.getAll();
                tableModel.setRowCount(0);
                if (kq.isEmpty()) {
                } else {
                    for (BorrowCard bc : kq) {
                        String maPM = String.valueOf(bc.getID());
                        String rName = bc.getReadername().toLowerCase();
                        String sName = bc.getStaffname().toLowerCase();
                        String sDate = bc.getStartDate().toString();
                        String eDate = bc.getExpReDate().toString();
                        
                        if(maPM.contains(keyword)||rName.contains(keyword)||sName.contains(keyword)||sDate.contains(keyword)||eDate.contains(keyword)){
                            Object[] row = { bc.getID(), bc.getReadername(), bc.getStartDate(), bc.getExpReDate(), bc.getStaffname() };
                            tableModel.addRow(row);
                        }
                    }
                }
            } else {
                showBC();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyDesign.MyButton btnChoMuon;
    private javax.swing.JComboBox<String> cbSach;
    private com.toedter.calendar.JDateChooser dtgNgayNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbBaoMat;
    private javax.swing.JLabel lbLine;
    private javax.swing.JLabel lbMaPhieuMuon;
    private MyDesign.PanelBorder panelBorder1;
    private MyDesign.PanelBorder panelBorder2;
    private MyDesign.PanelBorder_Basic panelBorder_Basic1;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTicketDetail;
    private MyDesign.MyTable tbSachKhaDung;
    private javax.swing.JLabel txtDocGia;
    private javax.swing.JLabel txtNgayMuon;
    private MyDesign.SearchText txtSearch;
    private javax.swing.JLabel txtSoLuong;
    private javax.swing.JLabel txtTacGia;
    private javax.swing.JLabel txtTenSach;
    private javax.swing.JLabel txtThuKho;
    private javax.swing.JLabel txtTienCoc;
    // End of variables declaration//GEN-END:variables
}
