/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import MyDesign.ScrollBar;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Vector;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import BLL.readerBLL;
import DTO.Readers;

/**
 *
 * @author QUANG DIEN
 */
public class Reader_GUI extends javax.swing.JPanel {
    private readerBLL rBLL;
    /**
     * Creates new form Reader_GUI
     */
    public Reader_GUI() {
        initComponents();
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        try{
            rBLL=new readerBLL();
            rBLL.updateFineDate();
            addDefault();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    }

    public void addDefault() throws Exception{
        Vector<Readers> arr=rBLL.getAll();
        for(int i=0;i<arr.size();i++){
            Readers acc=arr.get(i);
            int id=acc.getId();
            String name=acc.getName();
            String tel=acc.getTel();
            String address=acc.getAddress();
            LocalDate fineDate=acc.getFineDate();
            Boolean isLocked=acc.getisLocked();
            String isL="Mở";
            if(isLocked){
                isL="Khoá";
            }
            long daysBetween=0; 
            if(fineDate!=null) {
	            LocalDate cuDate=LocalDate.now();
	            daysBetween = ChronoUnit.DAYS.between(cuDate, fineDate);
            }        
            Object row[] = {i+1,id,name,tel,address,daysBetween,isL};
            tbDanhSachDocGia.addRow(row);
        }
    }
    
    public void findVal(String str) throws Exception {
    	Vector<Readers> arr=rBLL.allOutSearch(str);
    	if(arr.size()==0) {
    		JOptionPane.showMessageDialog(null,"Không tìm thấy độc giả theo yêu cầu");
    		return;
    	}
    	tbDanhSachDocGia.setRowCount(0);
    	for(int i=0;i<arr.size();i++){
            Readers acc=arr.get(i);
            int id=acc.getId();
            String name=acc.getName();
            String tel=acc.getTel();
            String address=acc.getAddress();
            LocalDate fineDate=acc.getFineDate();
            Boolean isLocked=acc.getisLocked();
            String isL="Mở";
            if(isLocked){
                isL="Khoá";
            }
            long daysBetween=0; 
            if(fineDate!=null) {
	            LocalDate cuDate=LocalDate.now();
	            daysBetween = ChronoUnit.DAYS.between(cuDate, fineDate);
            }        
            Object row[] = {i+1,id,name,tel,address,daysBetween,isL};
            tbDanhSachDocGia.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new MyDesign.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tbDanhSachDocGia = new MyDesign.MyTable();
        panelBorder_Basic1 = new MyDesign.PanelBorder_Basic();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiem = new MyDesign.SearchText();
        btnDocGiaMoi = new MyDesign.MyButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(127, 127, 127));
        jLabel5.setText("Danh sách độc giả");

        spTable.setBorder(null);

        tbDanhSachDocGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã độc giả", "Tên độc giả", "Số điện thoại", "Địa chỉ", "Số ngày khoá", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        spTable.setViewportView(tbDanhSachDocGia);
        
        tbDanhSachDocGia.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int row = tbDanhSachDocGia.getSelectedRow();
                    if (row >= 0) {
                        String cellValue = tbDanhSachDocGia.getValueAt(row, 1).toString();
                        int cellVal=Integer.parseInt(cellValue);
                        try {
	                        ReaderUpdateInfor_Dialog ruid=new ReaderUpdateInfor_Dialog(new javax.swing.JFrame(), true,cellVal,tbDanhSachDocGia);
	                        ruid.setVisible(true);
                        }catch(Exception ex) {
                        	JOptionPane.showMessageDialog(null,ex.getMessage());
                        }
                    }
                }
            }
        });
        
        txtTimKiem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String text = txtTimKiem.getText().trim();
                try {
					findVal(text);
				} catch (Exception e1) {
					// TODO Auto-generated catch block
					JOptionPane.showMessageDialog(null,e1.getMessage());
				}
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder_Basic1Layout = new javax.swing.GroupLayout(panelBorder_Basic1);
        panelBorder_Basic1.setLayout(panelBorder_Basic1Layout);
        panelBorder_Basic1Layout.setHorizontalGroup(
            panelBorder_Basic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder_Basic1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelBorder_Basic1Layout.setVerticalGroup(
            panelBorder_Basic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder_Basic1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder_Basic1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder_Basic1Layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnDocGiaMoi.setBackground(new java.awt.Color(22, 113, 221));
        btnDocGiaMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnDocGiaMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/action-add-white.png"))); // NOI18N
        btnDocGiaMoi.setText("Độc giả mới");
        btnDocGiaMoi.setToolTipText("");
        btnDocGiaMoi.setBorderColor(new java.awt.Color(22, 113, 221));
        btnDocGiaMoi.setColor(new java.awt.Color(22, 113, 221));
        btnDocGiaMoi.setColorClick(new java.awt.Color(153, 204, 255));
        btnDocGiaMoi.setColorOver(new java.awt.Color(22, 113, 221));
        btnDocGiaMoi.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDocGiaMoi.addActionListener(new ActionListener() {
        	 @Override
             public void actionPerformed(ActionEvent e){
        		 try {
	        		 ReaderAdd_Dialog rad=new ReaderAdd_Dialog(new javax.swing.JFrame(), true,tbDanhSachDocGia);
	        		 rad.setVisible(true);
        		 }catch(Exception ex) {
        			 JOptionPane.showMessageDialog(null,ex.getMessage());
        		 }
        	 }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBorder_Basic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnDocGiaMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelBorder_Basic1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDocGiaMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MyDesign.MyButton btnDocGiaMoi;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private MyDesign.PanelBorder panelBorder1;
    private MyDesign.PanelBorder_Basic panelBorder_Basic1;
    private javax.swing.JScrollPane spTable;
    private MyDesign.MyTable tbDanhSachDocGia;
    private MyDesign.SearchText txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
