/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import MyDesign.ScrollBar;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Random;

import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import BUS.BookBUS;
import BUS.AuthorBUS;
import BUS.CategoryBUS;
import BUS.DetailSupplyCardBUS;
import BUS.PublisherBUS;
import BUS.SupplyCardBUS;
import BUS.WarehouseBUS;
import DTO.entities.Author;
import DTO.entities.Category;
import DTO.entities.Warehouse;
import DTO.entities.Publisher;
import DTO.entities.Book1;
import DTO.entities.SupplyCard;
import DTO.entities.SupplyCardDetail;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import javax.swing.JTextField;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author QUANG DIEN
 */
public class WareHouseImport_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form WareHouseImport_Dialog
     */
    public WareHouseImport_Dialog(java.awt.Frame parent, boolean modal) throws SQLException, IOException, ClassNotFoundException {
        super(parent, modal);
        try {
            this.pack();
            initComponents();
            spTable.setVerticalScrollBar(new ScrollBar());
            spTable.getVerticalScrollBar().setBackground(Color.WHITE);
            spTable.getViewport().setBackground(Color.WHITE);
            JPanel p = new JPanel();
            p.setBackground(Color.WHITE);
            spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        } catch (IOException ex) {
            Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws SQLException, IOException, ClassNotFoundException{

        panelBorder_Statistic_Blue1 = new MyDesign.PanelBorder_Statistic_Blue();
        panelBorder_Basic1 = new MyDesign.PanelBorder_Basic();
        panelBorder2 = new MyDesign.PanelBorder();
        pnImageBook = new MyDesign.PanelBorder_Basic();
        lbImageBook = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLuuThongTin = new MyDesign.MyButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel8_1 = new javax.swing.JLabel();
        jLabel8_2 = new javax.swing.JLabel();
        txtTenSach = new MyDesign.MyTextField_Basic();
        txtISBN = new MyDesign.MyTextField_Basic();
        txtEdition = new MyDesign.MyTextField_Basic();
        txtGia = new MyDesign.MyTextField_Basic();
        txtSoLuong = new MyDesign.MyTextField_Basic();
        author = new AuthorBUS();
        List<Author> authorList = author.getAllName();
        cbTacGia = new javax.swing.JComboBox<>();
        lbThemTacGia = new javax.swing.JLabel();
        publisher = new PublisherBUS();
        final List<Publisher> publisherList = publisher.getAllName();
        cbNXB = new javax.swing.JComboBox<>();
        lbThemNXB = new javax.swing.JLabel();
        category = new CategoryBUS();
        List<Category> categoryList = category.getAllName();
        cbTheLoai = new javax.swing.JComboBox<>();
        lbThemTheLoai = new javax.swing.JLabel();
        panelBorder1 = new MyDesign.PanelBorder();
        jLabel9 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tbSachDuocNhap = new MyDesign.MyTable();
        btnNhapQuaSheet = new MyDesign.MyButton();
        jLabel10 = new javax.swing.JLabel();
        supplyCard = new SupplyCardBUS();
        List<SupplyCard> supplyCardList = supplyCard.getAllName();
        cbNhaCungCap = new javax.swing.JComboBox<>();
        lbThemNhaCungCap = new javax.swing.JLabel();
        lblicon_img = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTongChi = new javax.swing.JLabel();
        btnXacNhan = new MyDesign.MyButton();
        jLabel3 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelBorder2.setPreferredSize(new java.awt.Dimension(217, 327));

        pnImageBook.setPreferredSize(new java.awt.Dimension(137, 192));

        lbImageBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddImage.png"))); // NOI18N
        lbImageBook.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        lbImageBook.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JFileChooser fileChooser = new JFileChooser();
                fileChooser.setDialogTitle("Chọn tệp ảnh .png, .jpg");            
                FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp ảnh .png, .jpg", "png", "jpg");
                fileChooser.setFileFilter(filter);
                int result = fileChooser.showOpenDialog(null);
                if (result == JFileChooser.APPROVE_OPTION) {
                    String selectedImagePath = fileChooser.getSelectedFile().getAbsolutePath();
                    if(selectedImagePath==null)
                    {
                    	JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Không tìm thấy ảnh.","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                    	lbImageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddImage.png")));
                    }else {
                    	JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Đã chọn ảnh: " + selectedImagePath);
                        lbImageBook.setIcon(new javax.swing.ImageIcon(selectedImagePath));
                    }
                }
            }
        });
        
        
        javax.swing.GroupLayout pnImageBookLayout = new javax.swing.GroupLayout(pnImageBook);
        pnImageBook.setLayout(pnImageBookLayout);
        pnImageBookLayout.setHorizontalGroup(
            pnImageBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImageBook, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );
        pnImageBookLayout.setVerticalGroup(
            pnImageBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbImageBook, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel2.setText("Số lượng");

        btnLuuThongTin.setForeground(new java.awt.Color(44, 137, 247));
        btnLuuThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/action-save-white.png"))); // NOI18N
        btnLuuThongTin.setText("Lưu thông tin");
        btnLuuThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuThongTin.setPreferredSize(new java.awt.Dimension(177, 36));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel4.setText("Giá");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel5.setText("Thể loại");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel6.setText("NXB");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel7.setText("Tác giả");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel8.setText("Tên sách");
        
        txtTenSach.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        txtTenSach.setFont(new java.awt.Font("SansSerif", 1, 13));
        
        //GÕ ENTER SAU KHI NHẬP TÊN SÁCH
        txtTenSach.addKeyListener(new KeyListener() {
    			
    		@Override
    		public void keyTyped(KeyEvent e) {
    			// TODO Auto-generated method stub
    		}
    			
    		@Override
    		public void keyReleased(KeyEvent e) {
    			// TODO Auto-generated method stub
    				
    		}
    			
    		@Override
    		public void keyPressed(KeyEvent e) {
    			final String name = txtTenSach.getText();
    			// TODO Auto-generated method stub
    			try {
					if(e.getKeyCode()==KeyEvent.VK_ENTER)
					{
						String img = supplyCard.getByImg(name);
						String isbn = supplyCard.getByISBN(name);
						File imageFile = new File(img);
//						if(isbn!=null)
//						{
//							txtISBN.setText(isbn);
//						}
//						else {
//							System.out.println("Không thể tìm thấy mã ISBN.");
//						}
			            if (imageFile.exists() && imageFile.canRead()) {
			                try {
			                    BufferedImage image = ImageIO.read(imageFile);
			                    if (image != null && isbn!=null) {
			                    	//TRUYỀN ĐƯỜNG DẪN TUYỆT ĐỐI (ĐỐI VỚI MÁY MÌNH, CÒN MÁY KHÁC NỄU CHẠY ĐƯỢC THÌ KHỎI SỬA DB)
			                        lbImageBook.setIcon(new javax.swing.ImageIcon(image));
			                        txtISBN.setText(isbn);
			                        txtISBN.setEditable(false);
			                    } else {
			                        System.out.println("Không thể đọc hình ảnh.");
			                        System.out.println("Không thể tìm thấy mã ISBN.");
			                    }
			                } catch (IOException e1) {
			                    System.out.println(e1);
			                    JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Không thể đọc tệp ảnh.", "Lỗi", JOptionPane.ERROR_MESSAGE);
			                }
			            } else {
			                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Tệp ảnh không tồn tại hoặc không thể đọc.", "Lỗi", JOptionPane.ERROR_MESSAGE);
			            }
			        }
				} catch (Exception e1) {
					// TODO Auto-generated catch block
    				JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Tên sách không đúng hoặc Tên Sách không tồn tại.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					System.out.println(e1);
				}
    		}
    	});       
        
        txtGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        txtGia.setFont(new java.awt.Font("SansSerif", 1, 13));
        
        //GÕ ENTER KIỂM TRA NỘI DUNG CỦA TEXTFIELD GIÁ
        txtGia.addKeyListener(new KeyListener() {
			
			@Override
			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				final String g = txtGia.getText();
				if(e.getKeyCode()==KeyEvent.VK_ENTER)
				{
					if(isAlpha(g))
					{
						JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Nội dung là số không phải là chữ!","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					}
					if(isNumeric(g))
					{
						if(Integer.parseInt(g)<19000)
						{
							JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Giá không được thấp hơn 19k.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
						}
					}
					else {
						JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Nội dung không thể chứa cả chữ và số. ","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					}
				}
			}
		});
        
        txtSoLuong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        txtSoLuong.setFont(new java.awt.Font("SansSerif", 1, 13));
        
        //GÕ ENTER KIỂM TRA TEXT SỐ LƯỢNG
        txtSoLuong.addKeyListener(new KeyListener() {
			
			@Override
			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
        		final String sl = txtSoLuong.getText();
        		if(e.getKeyCode()==KeyEvent.VK_ENTER)
        		{
        			if(isAlpha(sl))
					{
						JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Nội dung là số không phải là chữ.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					}
					if(isNumeric(sl))
					{
						if(Integer.parseInt(sl)<=0)
						{
							JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Số lượng không được nhỏ hơn bằng 0.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
						}
					}
					else {
						JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Nội dung không thể chứa cả chữ và số. ","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					}
        		}
			}
		});
        
        // KIỂM TRA TEXT GIÁ
        txtSoLuong.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e)
        	{
        		if(txtGia.getText()!=null)
        		{
        			if(isAlpha(txtGia.getText()))
        			{
        				JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Giá phải là số không phải là chữ.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
        			}
        			else if(isNumeric(txtGia.getText()))
        			{
        				if(Integer.parseInt(txtGia.getText())<19000)
        				{
        					JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Giá không dưới 19k.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
        				}
        			}
        			else {
        				JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Giá không chứa chữ và số.","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
        			}
        		}
        	}
        });
   
        cbTacGia.setBackground(new java.awt.Color(246, 250, 255));
        cbTacGia.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
//        cbTacGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tác giả" }));
        for(Author item : authorList)
        {
        	cbTacGia.addItem(item.getName());
        }
        cbTacGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        cbTacGia.setOpaque(true);
        cbTacGia.setPreferredSize(new java.awt.Dimension(77, 28));

        lbThemTacGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemTacGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        lbThemTacGia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lbThemTacGia.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        lbThemTacGia.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e)
        	{
        		if(e.getClickCount()==1 || e.getClickCount()==2)
        		{
        			setVisible(false);
        			WareHouseAddReader_Dialog r;
                    try {
                        r = new WareHouseAddReader_Dialog(null, "warehouse" ,rootPaneCheckingEnabled);
                        r.setVisible(true);
                    } catch (ClassNotFoundException | SQLException | IOException e1) {
                        // TODO Auto-generated catch block
                        e1.printStackTrace();
                    }

        			
        		}
        	}
		});

        cbNXB.setBackground(new java.awt.Color(246, 250, 255));
        cbNXB.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
//        cbNXB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NXB" }));
        for(Publisher item : publisherList)
        {
        	cbNXB.addItem(item.getName());
        }
        cbNXB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        cbNXB.setOpaque(true);
        cbNXB.setPreferredSize(new java.awt.Dimension(77, 28));

        lbThemNXB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        lbThemNXB.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lbThemNXB.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        lbThemNXB.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e)
        	{
        		if(e.getClickCount()==1 || e.getClickCount()==2)
        		{
        			hide();
        			WareHouseAddNXB_Dialog r;
                    try {
                        r = new WareHouseAddNXB_Dialog(null,"warehouse", rootPaneCheckingEnabled);
                        r.setVisible(true);
                    } catch (ClassNotFoundException | SQLException | IOException e1) {
                        // TODO Auto-generated catch block
                        e1.printStackTrace();
                    }

        			
        		}
        	}
		});
        
        cbTheLoai.setBackground(new java.awt.Color(246, 250, 255));
        cbTheLoai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
//        cbTheLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thể loại" }));
        for(Category item : categoryList)
        {
        	cbTheLoai.addItem(item.getName());
        }
        cbTheLoai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        cbTheLoai.setOpaque(true);
        cbTheLoai.setPreferredSize(new java.awt.Dimension(77, 28));

        lbThemTheLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemTheLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        lbThemTheLoai.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lbThemTheLoai.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        lbThemTheLoai.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e)
        	{
        		if(e.getClickCount()==1 || e.getClickCount()==2)
        		{
        			hide();
        			WareHouseAddTypeBook_Dialog r;
                    try {
                        r = new WareHouseAddTypeBook_Dialog(null,"warehouse", rootPaneCheckingEnabled);
                        r.setVisible(true);
                    } catch (ClassNotFoundException | SQLException | IOException e1) {
                        // TODO Auto-generated catch block
                        e1.printStackTrace();
                    }
        			
        		}
        	}
		});
        
        jLabel8_1.setText("Edition");
        jLabel8_1.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        
        txtEdition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        txtEdition.setFont(new java.awt.Font("SansSerif", 1, 13));
        
        jLabel8_2.setText("ISBN");
        jLabel8_2.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        
        txtISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        txtISBN.setFont(new java.awt.Font("SansSerif", 1, 13));
        
        // GÕ ENTER KIỂM TRA TEXT ISBN
        txtISBN.addKeyListener(new KeyListener() {
			
			@Override
			public void keyTyped(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyReleased(KeyEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void keyPressed(KeyEvent e) {
				// TODO Auto-generated method stub
				final String isbn = txtISBN.getText();
				if(e.getKeyCode()==KeyEvent.VK_ENTER)
				{
					if(isAlpha(isbn))
					{
						JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Nội dung là số không phải là chữ!","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					}
					else {
						JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Nội dung không thể chứa cả chữ và số. ","Cảnh Báo",JOptionPane.WARNING_MESSAGE);
					}
				}
			}
		});
        
        lblicon_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblicon_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        lblicon_img.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lblicon_img.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        lblicon_img.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				
            }
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    if (whs == null) {
                        whs = new WareHouseScanner_Dialog();
                    }
                    whs.setVisible(true);
                    txtISBN.setText(whs.txtField.getText());
                }
                else {
                	whs.setVisible(false);
                	txtISBN.setEditable(false);
                }
			}
		});
        
        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2Layout.setHorizontalGroup(
        	panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder2Layout.createSequentialGroup()
        			.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panelBorder2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addGap(16)
        							.addComponent(txtSoLuong, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        						.addComponent(btnLuuThongTin, GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addComponent(jLabel5)
        							.addGap(26)
        							.addComponent(cbTheLoai, 0, 114, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lbThemTheLoai, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addComponent(jLabel4)
        							.addGap(54)
        							.addComponent(txtGia, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel8)
        								.addComponent(jLabel7))
        							.addGap(18)
        							.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(panelBorder2Layout.createSequentialGroup()
        									.addComponent(cbTacGia, 0, 114, Short.MAX_VALUE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(lbThemTacGia, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        								.addComponent(txtTenSach, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(46)
        							.addComponent(cbNXB, 0, 114, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lbThemNXB, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))))
        				.addGroup(panelBorder2Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel8_1, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(txtEdition, GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
        				.addGroup(panelBorder2Layout.createSequentialGroup()
        					.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(jLabel8_2, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(txtISBN, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addGap(40)
        							.addComponent(pnImageBook, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblicon_img, GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
        	panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder2Layout.createSequentialGroup()
        			.addGap(18)
        			.addComponent(pnImageBook, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
        			.addGroup(panelBorder2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtISBN, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8_2, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblicon_img, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(panelBorder2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(panelBorder2Layout.createSequentialGroup()
        					.addGroup(panelBorder2Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(txtEdition, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel8_1, GroupLayout.PREFERRED_SIZE, 18, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(panelBorder2Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(panelBorder2Layout.createSequentialGroup()
        							.addGroup(panelBorder2Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jLabel8)
        								.addComponent(txtTenSach, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addComponent(jLabel7))
        						.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        							.addComponent(lbThemTacGia, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        							.addComponent(cbTacGia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGap(18)
        					.addComponent(jLabel6))
        				.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(lbThemNXB, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        					.addComponent(cbNXB, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panelBorder2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel5)
        				.addGroup(panelBorder2Layout.createParallelGroup(Alignment.LEADING)
        					.addComponent(lbThemTheLoai, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        					.addComponent(cbTheLoai, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(panelBorder2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(txtGia, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(panelBorder2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtSoLuong, GroupLayout.PREFERRED_SIZE, 26, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(btnLuuThongTin, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(16))
        );
        panelBorder2.setLayout(panelBorder2Layout);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(127, 127, 127));
        jLabel9.setText("Sách được nhập");

        spTable.setBorder(null);
//        final DefaultTableModel model = (DefaultTableModel) tbSachDuocNhap.getModel();
        tbSachDuocNhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ISBN", "Tên sách", "Tác giả", "Tái Bản", "NXB", "Thể loại", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTable.setViewportView(tbSachDuocNhap);
        
        //ACTION LƯU THÔNG TIN VÀ KIỂM TRA TEXT SỐ LƯỢNG
        
        btnLuuThongTin.addActionListener(new ActionListener() {
			
			@Override
			
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				edition = txtEdition.getText();
				tensach = txtTenSach.getText();
				gia = txtGia.getText();
				soluong = txtSoLuong.getText();
				isbn = txtISBN.getText();
				if(isTextFieldEmpty(txtEdition))
				{
					JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Vui lòng điền đầy đủ thông tin.","Cảnh báo",JOptionPane.WARNING_MESSAGE);
				}
				else if(isTextFieldEmpty(txtTenSach))
				{
					JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Vui lòng điền đầy đủ thông tin.","Cảnh báo",JOptionPane.WARNING_MESSAGE);
				}
				else if(isTextFieldEmpty(txtGia))
				{
					JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Vui lòng điền đầy đủ thông tin.","Cảnh báo",JOptionPane.WARNING_MESSAGE);
				}
				else if(isTextFieldEmpty(txtSoLuong))
				{
					JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Vui lòng điền đầy đủ thông tin.","Cảnh báo",JOptionPane.WARNING_MESSAGE);
				}else {
					DefaultTableModel model = (DefaultTableModel) tbSachDuocNhap.getModel();
					tgia = String.valueOf(cbTacGia.getSelectedItem());
					nxb = String.valueOf(cbNXB.getSelectedItem());
					theloai = String.valueOf(cbTheLoai.getSelectedItem());
					ncc = String.valueOf(cbNhaCungCap.getSelectedItem());
					String[] rowData = {Integer.toString(model.getRowCount() + 1), isbn, tensach, tgia, edition, nxb, theloai, gia, soluong};
					model.addRow(rowData);
					tongchi = tongchi + (Integer.parseInt(gia) * Integer.parseInt(soluong));
					tongsoluong = tongsoluong + (Integer.parseInt(soluong));
					txtTongChi.setText(String.valueOf(tongchi+"đ"));
					lbImageBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AddImage.png")));
					txtISBN.setText("");
					txtEdition.setText("");
					txtTenSach.setText("");
					txtGia.setText("");
					txtSoLuong.setText("");
				}
			}
        });
        
        //ACTION XỬ LÝ XÓA TRONG JTABLE
        final JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem menuItemXoa = new JMenuItem("Xóa");
        JMenuItem menuItemNhap = new JMenuItem("Nhập thêm sách");
        menuItemXoa.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				int dialogResult = JOptionPane.showConfirmDialog(JOptionPane.getRootFrame(), "Bạn có chắc là muốn xóa không?","Xác nhận",JOptionPane.YES_NO_OPTION);
				if(dialogResult == JOptionPane.YES_OPTION)
				{
					DefaultTableModel model = (DefaultTableModel) tbSachDuocNhap.getModel();
					int selectedRow = tbSachDuocNhap.getSelectedRow();
					if(selectedRow >= 0)
					{
						Object value = tbSachDuocNhap.getValueAt(selectedRow, 7);
						Object value1 = tbSachDuocNhap.getValueAt(selectedRow, 8);
						if(value !=null && value1 !=null)
						{
							gia = value.toString();
							soluong = value1.toString();
							tongchi = tongchi - (Integer.parseInt(gia)*Integer.parseInt(soluong));
							txtTongChi.setText(String.valueOf(tongchi));
							tongsoluong = tongsoluong - (Integer.parseInt(soluong));
						}
						model.removeRow(selectedRow);
						 // Cập nhật lại giá trị "STT" cho tất cả các dòng còn lại
				        for (int i = 0; i < model.getRowCount(); i++) {
				            model.setValueAt(i + 1, i, 0); // Cập nhật cột "STT" (cột 0)
				        }
					}
				}
			}
		});
        
        menuItemNhap.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				txtTenSach.setEditable(true);
				txtGia.setEditable(true);
				txtSoLuong.setEditable(true);
				txtEdition.setEditable(true);
				txtISBN.setEditable(true);
				cbNXB.setEnabled(true);
				cbTacGia.setEnabled(true);
				cbTheLoai.setEnabled(true);
			}
		});
        
        popupMenu.add(menuItemXoa);
        popupMenu.add(menuItemNhap);
        tbSachDuocNhap.setComponentPopupMenu(popupMenu);
        
        tbSachDuocNhap.addMouseListener(new MouseAdapter() {
        	 public void mousePressed(MouseEvent e) {
                 if (SwingUtilities.isRightMouseButton(e)) {
                     int row = tbSachDuocNhap.rowAtPoint(e.getPoint());
                     tbSachDuocNhap.setRowSelectionInterval(row, row);
                 }
             }
		});
        
        tbSachDuocNhap.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e)
        	{
        		if(e.getClickCount() == 1 || e.getClickCount() == 2)
        		{
        			DefaultTableModel model = (DefaultTableModel) tbSachDuocNhap.getModel();
        			int seclectedRow = tbSachDuocNhap.getSelectedRow();
        			if(seclectedRow >= 0)
        			{
        				Object isbn = tbSachDuocNhap.getValueAt(seclectedRow, 1).toString();
        				Object sach = tbSachDuocNhap.getValueAt(seclectedRow, 2).toString();
        				Object tg = tbSachDuocNhap.getValueAt(seclectedRow, 3);
        				Object ed = tbSachDuocNhap.getValueAt(seclectedRow, 4).toString();
        				Object nhaxuatban = tbSachDuocNhap.getValueAt(seclectedRow, 5);
        				Object tl = tbSachDuocNhap.getValueAt(seclectedRow, 6);
        				Object g = tbSachDuocNhap.getValueAt(seclectedRow, 7).toString();
        				Object sl = tbSachDuocNhap.getValueAt(seclectedRow, 8).toString();
        				if(sach!=null && tg!=null && nhaxuatban!=null && tl!=null && g!=null && sl!=null)
        				{
    			            txtGia.setText(String.valueOf(g));
    			            txtGia.setEditable(false);
    			            txtSoLuong.setText(String.valueOf(sl));
    			            txtSoLuong.setEditable(false);
        					txtTenSach.setText(String.valueOf(sach));
        					txtTenSach.setEditable(false);
        					txtEdition.setText(String.valueOf(ed));
        					txtEdition.setEditable(false);
        					txtISBN.setText(String.valueOf(isbn));
        					txtISBN.setEditable(false);
        					
        					cbTacGia.setSelectedItem(tg);
        					cbTacGia.setEnabled(false);
        					cbTheLoai.setSelectedItem(tl);
        					cbTheLoai.setEnabled(false);
        					cbNXB.setSelectedItem(nhaxuatban);
            				cbNXB.setEnabled(false);
            				cbNhaCungCap.setSelectedItem(ncc);
        					cbNhaCungCap.setEnabled(false);
        					
        					String img;
                            try {
                                img = supplyCard.getByImg(String.valueOf(sach));
                                File imageFile = new File(img);
                                if (imageFile.exists() && imageFile.canRead()) {
                                    try {
                                        BufferedImage image = ImageIO.read(imageFile);
                                        if (image != null) {
                                            //TRUYỀN ĐƯỜNG DẪN TUYỆT ĐỐI (ĐỐI VỚI MÁY MÌNH, CÒN MÁY KHÁC NỄU CHẠY ĐƯỢC THÌ KHỎI SỬA DB)
                                            lbImageBook.setIcon(new javax.swing.ImageIcon(image));
                                        }
                                    } catch (IOException e1) {
                                        JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Không thể đọc tệp ảnh.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                                    }
                                } else {
                                    JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Tệp ảnh không tồn tại hoặc không thể đọc.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                                }
                            } catch (SQLException e1) {
                                // TODO Auto-generated catch block
                                e1.printStackTrace();
                            } catch (IOException e1) {
                                // TODO Auto-generated catch block
                                e1.printStackTrace();
                            }
    						
        				}
        			}
        		}
        	}
		});
        
        btnNhapQuaSheet.setForeground(new java.awt.Color(22, 113, 221));
        btnNhapQuaSheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/action-import.png"))); // NOI18N
        btnNhapQuaSheet.setText("Nhập qua sheet");
        btnNhapQuaSheet.setToolTipText("");
        btnNhapQuaSheet.setColorClick(new java.awt.Color(153, 204, 255));
        btnNhapQuaSheet.setColorOver(new java.awt.Color(102, 204, 255));
        btnNhapQuaSheet.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        
        btnNhapQuaSheet.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				try {
	                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
	                Random random = new Random();
	                String randomFileName = "C:\\Users\\Hi\\Documents\\Excel\\SupplyCard_" + dateFormat.format(new Date()) + "_" + random.nextInt(1000) + ".xlsx";

	                File excelFile = new File(randomFileName);
	                XSSFWorkbook workbook = new XSSFWorkbook();
	                XSSFSheet sheet = workbook.createSheet(String.valueOf(dateFormat.format(new Date())));
	                XSSFRow titleRow = sheet.createRow(0);
	                for(int j = 0; j < tbSachDuocNhap.getColumnCount(); j++)
	                {
	                	XSSFCell cell = titleRow.createCell(j);
	                	cell.setCellValue(tbSachDuocNhap.getColumnName(j));
	                }
	                for (int i = 0; i < tbSachDuocNhap.getRowCount(); i++) {
	                    XSSFRow row = sheet.createRow(i+1);
	                    for (int j = 0; j < tbSachDuocNhap.getColumnCount(); j++) {
	                        XSSFCell cell = row.createCell(j);
	                        cell.setCellValue(tbSachDuocNhap.getValueAt(i, j).toString());
	                    }
	                }
	                FileOutputStream outFile = new FileOutputStream(excelFile);
	                workbook.write(outFile);
	                outFile.close();
	                workbook.close();
	                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Dữ liệu đã được ghi vào tệp Excel: " + randomFileName);
	            } catch (Exception ex) {
	                ex.printStackTrace();
	                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Lỗi khi ghi dữ liệu vào tệp Excel: " + ex.getMessage());
	            }
			}
		});
        
        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1Layout.setHorizontalGroup(
        	panelBorder1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelBorder1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(panelBorder1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(spTable, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        				.addGroup(panelBorder1Layout.createSequentialGroup()
        					.addComponent(jLabel9)
        					.addPreferredGap(ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
        					.addComponent(btnNhapQuaSheet, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
        	panelBorder1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelBorder1Layout.createSequentialGroup()
        			.addGap(8)
        			.addGroup(panelBorder1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnNhapQuaSheet, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(spTable, GroupLayout.PREFERRED_SIZE, 401, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(27, Short.MAX_VALUE))
        );
        panelBorder1.setLayout(panelBorder1Layout);

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nhà cung cấp");

        cbNhaCungCap.setBackground(new java.awt.Color(246, 250, 255));
        cbNhaCungCap.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
//        cbNhaCungCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhà cung cấp" }));
        for(Publisher item : publisherList)
        {
        	cbNhaCungCap.addItem(item.getName());
        }
        cbNhaCungCap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        cbNhaCungCap.setOpaque(true);
        cbNhaCungCap.setPreferredSize(new java.awt.Dimension(77, 28));

        lbThemNhaCungCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        lbThemNhaCungCap.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        lbThemNhaCungCap.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        lbThemNhaCungCap.addMouseListener(new MouseAdapter() {
        	public void mouseClicked(MouseEvent e)
        	{
        		if(e.getClickCount()==1 || e.getClickCount()==2)
        		{
        			hide();
        			WareHouseAddNCC_Dialog r;
                    try {
                        r = new WareHouseAddNCC_Dialog(null,"warehouse" ,rootPaneCheckingEnabled);
                        r.setVisible(true);
                    } catch (ClassNotFoundException | SQLException | IOException e1) {
                        // TODO Auto-generated catch block
                        e1.printStackTrace();
                    }
        			
        		}
        	}
		});
        
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Tổng chi");

        txtTongChi.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        txtTongChi.setText("0đ");

        btnXacNhan.setBackground(new java.awt.Color(22, 113, 221));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setBorderColor(new java.awt.Color(22, 113, 221));
        btnXacNhan.setColor(new java.awt.Color(22, 113, 221));
        btnXacNhan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        
        btnXacNhan.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				int rs = JOptionPane.showConfirmDialog(JOptionPane.getRootFrame(), "Bạn có muốn nhập qua sheet không?","Xác nhận",JOptionPane.YES_NO_OPTION);
				if(rs == JOptionPane.YES_OPTION)
				{
					try {
		                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		                Random random = new Random();
		                String randomFileName = "C:\\Users\\Hi\\Documents\\Excel\\SupplyCard_" + dateFormat.format(new Date()) + "_" + random.nextInt(1000) + ".xlsx";

		                File excelFile = new File(randomFileName);
		                XSSFWorkbook workbook = new XSSFWorkbook();
		                XSSFSheet sheet = workbook.createSheet(String.valueOf(dateFormat.format(new Date())));
		                XSSFRow titleRow = sheet.createRow(0);
		                for(int j = 0; j < tbSachDuocNhap.getColumnCount(); j++)
		                {
		                	XSSFCell cell = titleRow.createCell(j);
		                	cell.setCellValue(tbSachDuocNhap.getColumnName(j));
		                }
		                for (int i = 0; i < tbSachDuocNhap.getRowCount(); i++) {
		                    XSSFRow row = sheet.createRow(i+1);
		                    for (int j = 0; j < tbSachDuocNhap.getColumnCount(); j++) {
		                        XSSFCell cell = row.createCell(j);
		                        cell.setCellValue(tbSachDuocNhap.getValueAt(i, j).toString());
		                    }
		                }
		                FileOutputStream outFile = new FileOutputStream(excelFile);
		                workbook.write(outFile);
		                outFile.close();
		                workbook.close();
		                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Dữ liệu đã được ghi vào tệp Excel: " + randomFileName);
		            } catch (Exception ex) {
		                ex.printStackTrace();
		                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Lỗi khi ghi dữ liệu vào tệp Excel: " + ex.getMessage());
		            }
				}
				else {
				    // LƯU DỮ LIỆU VÀO DATABASE
		            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
		            Date currentDate = new Date();
		            Timestamp timestamp = new Timestamp(currentDate.getTime());
		            
		            // KHỞI TẠO ĐỐI TƯỢNG
		            Book1 sach = new Book1();
		            Warehouse k = new Warehouse();
		            SupplyCardDetail d = new SupplyCardDetail();
		            
		            // TẠO 1 PHIẾU SUPPLYCARD
		            SupplyCard s = new SupplyCard();
	                s.setSupDate(timestamp);
	                s.setProvider(String.valueOf(cbNhaCungCap.getSelectedItem()));
	                s.setTongchi(tongchi);
                    try {
                        scB.saveSC(s);
                    } catch (SQLException | IOException e1) {
                        
                    }
	                
		            
	                int bookID, scID, pubID,idBook;
	                
				    try {
						for (int i = 0; i < tbSachDuocNhap.getRowCount(); i++) {
						    isbn = tbSachDuocNhap.getValueAt(i, 1).toString();
						    tensach = tbSachDuocNhap.getValueAt(i, 2).toString();
						    tgia = tbSachDuocNhap.getValueAt(i, 3).toString();
						    edition = tbSachDuocNhap.getValueAt(i, 4).toString();
						    nxb = tbSachDuocNhap.getValueAt(i, 5).toString();
						    theloai = tbSachDuocNhap.getValueAt(i, 6).toString();
						    gia = tbSachDuocNhap.getValueAt(i, 7).toString();
						    soluong = tbSachDuocNhap.getValueAt(i, 8).toString();
						    bookID = supplyCard.getByNameBook(tensach);
						    idBook = supplyCard.getByIDBook();
						    scID = supplyCard.getByID();
						    pubID = supplyCard.getByPublisherID(nxb);
						    if (bookID == 0) {
						      // TRƯỜNG HỢP SÁCH MỚI
						      sach.setTenSach(tensach);
						      bB.saveInfo(sach);

						      k.setIsbn(isbn);
						      k.setBookID(bookID);
						      k.setStoreNum(Integer.parseInt(soluong));
						      k.setEdition(edition);
						      k.setPublisherID(pubID);
						      k.setCost(Long.parseLong(gia));
						      cB.savecpB(k);

					          d.setScID(scID);
						      d.setISBN(isbn);
						      d.setNum(Integer.parseInt(soluong));
						      dscB.saveDSC(d);

						    } else {
						      // TRƯỜNG HỢP SÁCH CŨ
						      k.setStoreNum(Integer.parseInt(soluong));
						      k.setIsbn(isbn);
						      cB.saveOldBook(k);

						      d.setScID(scID);
						      d.setISBN(isbn);
						      d.setNum(Integer.parseInt(soluong));
						      dscB.saveDSC(d);

						      }
						  }
					} catch (ClassNotFoundException | SQLException | IOException | NumberFormatException e1) {
						 JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Thêm dữ liệu thất bại.", "Thông Báo", JOptionPane.ERROR_MESSAGE);
				         System.out.println(e1);
					}
				    JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), "Thêm dữ liệu thành công.", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
				}
			}
		});
        
        javax.swing.GroupLayout panelBorder_Basic1Layout = new javax.swing.GroupLayout(panelBorder_Basic1);
        panelBorder_Basic1Layout.setHorizontalGroup(
        	panelBorder_Basic1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panelBorder2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panelBorder_Basic1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        					.addGroup(panelBorder_Basic1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(cbNhaCungCap, GroupLayout.PREFERRED_SIZE, 151, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel10))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lbThemNhaCungCap, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        				.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        					.addGroup(panelBorder_Basic1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtTongChi)
        						.addComponent(jLabel11))
        					.addGap(346)
        					.addComponent(btnXacNhan, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        				.addComponent(panelBorder1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        panelBorder_Basic1Layout.setVerticalGroup(
        	panelBorder_Basic1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        			.addGap(20)
        			.addGroup(panelBorder_Basic1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(panelBorder2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        				.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        					.addComponent(panelBorder1, GroupLayout.PREFERRED_SIZE, 461, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        					.addGroup(panelBorder_Basic1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        							.addGroup(panelBorder_Basic1Layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(panelBorder_Basic1Layout.createSequentialGroup()
        									.addComponent(jLabel10)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(cbNhaCungCap, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        								.addComponent(lbThemNhaCungCap, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
        							.addGap(23)
        							.addComponent(jLabel11)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(txtTongChi, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        						.addComponent(btnXacNhan, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE))))
        			.addGap(31))
        );
        panelBorder_Basic1.setLayout(panelBorder_Basic1Layout);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/warehouse-white.png"))); // NOI18N
        jLabel3.setText("Đơn nhập");

        javax.swing.GroupLayout panelBorder_Statistic_Blue1Layout = new javax.swing.GroupLayout(panelBorder_Statistic_Blue1);
        panelBorder_Statistic_Blue1.setLayout(panelBorder_Statistic_Blue1Layout);
        panelBorder_Statistic_Blue1Layout.setHorizontalGroup(
            panelBorder_Statistic_Blue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder_Statistic_Blue1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder_Statistic_Blue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addComponent(panelBorder_Basic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder_Statistic_Blue1Layout.setVerticalGroup(
            panelBorder_Statistic_Blue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder_Statistic_Blue1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder_Basic1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panelBorder_Statistic_Blue1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(panelBorder_Statistic_Blue1, GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Actions
    public static boolean isNumeric(String str) {
        return str.matches("-?\\d+(\\.\\d+)?");
    }
    public static boolean isAlpha(String str) {
        return str.matches("[a-zA-Z]+");
    }
    public boolean isTextFieldEmpty(JTextField textField) {
        return textField.getText().trim().isEmpty();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    WareHouseImport_Dialog dialog = new WareHouseImport_Dialog(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(WareHouseImport_Dialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private MyDesign.MyButton btnLuuThongTin;
    private MyDesign.MyButton btnNhapQuaSheet;
    private MyDesign.MyButton btnXacNhan;
    protected javax.swing.JComboBox<String> cbNXB;
    protected javax.swing.JComboBox<String> cbNhaCungCap;
    protected javax.swing.JComboBox<String> cbTacGia;
    protected javax.swing.JComboBox<String> cbTheLoai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel8_1;
    private javax.swing.JLabel jLabel8_2;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JLabel lbImageBook;
    private javax.swing.JLabel lbThemNXB;
    private javax.swing.JLabel lbThemNhaCungCap;
    private javax.swing.JLabel lbThemTacGia;
    private javax.swing.JLabel lbThemTheLoai;
    private javax.swing.JLabel lblicon_img;
    private MyDesign.PanelBorder panelBorder1;
    private MyDesign.PanelBorder panelBorder2;
    private MyDesign.PanelBorder_Basic panelBorder_Basic1;
    private MyDesign.PanelBorder_Statistic_Blue panelBorder_Statistic_Blue1;
    private MyDesign.PanelBorder_Basic pnImageBook;
    private javax.swing.JScrollPane spTable;
    private MyDesign.MyTable tbSachDuocNhap;
    private MyDesign.MyTextField_Basic txtGia;
    private MyDesign.MyTextField_Basic txtSoLuong;
    private static MyDesign.MyTextField_Basic txtTenSach;
    private javax.swing.JLabel txtTongChi;
    private AuthorBUS author;
    private PublisherBUS publisher;
    private CategoryBUS category;
    private static SupplyCardBUS supplyCard;
    private static DetailSupplyCardBUS detailSC;
    private static WarehouseBUS cpBook;
    protected long tongchi = 0;
    private int tongsoluong =0;
    private String gia, soluong;
    private String[] rowdata;
    private String tensach;
    private String tgia, nxb, ncc, theloai, edition, isbn;
    private Date supDate;
    private MyDesign.MyTextField_Basic txtEdition;
    public MyDesign.MyTextField_Basic txtISBN;
    private WarehouseBUS cB = new WarehouseBUS();
    private SupplyCardBUS scB = new SupplyCardBUS() ;
    private DetailSupplyCardBUS dscB = new DetailSupplyCardBUS() ;
    private BookBUS bB = new BookBUS();
    private WareHouseScanner_Dialog whs;
}
